server:
  port: 8889
spring:
  datasource:
    url: jdbc:postgresql://google/todoapp-388214:us-central1:todopostgres?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=todoapp-388214:us-central1:todopostgres&useSSL=false
    driver-class-name: org.postgresql.Driver
    username: todo_user
    password: todo_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
